// Generated by CoffeeScript 1.8.0
(function() {
  var Logger, config,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  config = require('./config.js');

  Logger = (function(_super) {
    __extends(Logger, _super);


    /*
      @param file file path for log
      @param fileSize размер файла после чего запускать rotate 0 - unlimited
      @param count - количество файлов для rotate 0 - отключено
     */

    function Logger() {
      Logger.__super__.constructor.call(this, config.getLogPath() + 'sigma.log', config.getLogSize(), config.getLogRotate());
    }

    return Logger;

  })(require('./log.js'));

  module.exports = new Logger();

}).call(this);
