// Generated by CoffeeScript 1.8.0
(function() {
  var cluster, main;

  cluster = require('cluster');

  console.log('Starting App');

  if (cluster.isMaster) {
    console.log('Forking in Master');
    cluster.fork();
    cluster.on('exit', function(worker, code, signal) {
      return console.log('Error happened, fork');
    });
  }

  if (cluster.isWorker) {
    console.log('Worker begin main');
    main = require('./server.js');
  }

}).call(this);
