// Generated by CoffeeScript 1.8.0
(function() {
  var SerialPort, Sigma, config;

  SerialPort = require("serialport").SerialPort;

  config = require('./config.js');

  Sigma = (function() {
    function Sigma() {
      this.port = new SerialPort(config.getComPort(), {}, false);
    }

    Sigma.prototype.writeLine = function() {
      return this.port.open((function(_this) {
        return function(err) {
          return _this.port.write(function(err, res) {});
        };
      })(this));
    };

    return Sigma;

  })();

  module.exports(new Sigma);

}).call(this);
